name: LangManager
main: matiasdamian\LangManager\Main
version: 1.0.5
api: [5.0.0]
author: matiasdamian
load: STARTUP
description: A language management plugin for PocketMine-MP with multi-language support and variable translation.
permissions:
  langmanager.lang:
    default: true
    description: Allows you to change your language